; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.41"

; Modules
projects[admin_menu][version] = "3.0-rc5"

projects[ctools][version] = "1.9"

projects[entity][version] = "1.6"

projects[media][version] = "1.5"

projects[google_analytics][version] = "2.1"

projects[i18n][version] = "1.13"

projects[imce][version] = "1.9"

projects[imce_wysiwyg][version] = "1.0"

projects[media_flickr][version] = "1.0-alpha4"

projects[media_vimeo][version] = "2.1"

projects[media_youtube][version] = "3.0"

projects[pathauto][version] = "1.3"

projects[pathologic][version] = "2.12"

projects[socialmedia][version] = "1.0-beta15"

projects[token][version] = "1.6"

projects[variable][version] = "2.5"

projects[views][version] = "3.13"

projects[views_slideshow][version] = "3.1"

projects[webform][version] = "3.24"

projects[widgets][version] = "1.0-rc1"

projects[wysiwyg][version] = "2.2"

projects[link][version] = "1.4"

; Themes
projects[zen][version] = "5.6"

; Modules
projects[blink_modules][download][type] = "git"
projects[blink_modules][download][url] = "git://github.com/neontribe/blink_modules.git"
projects[blink_modules][subdir] = "custom"
projects[blink_modules][type] = "module"

; Themes
projects[bananalink][download][type] = "git"
projects[bananalink][download][url] = "git://github.com/neontribe/blink_theme.git"
projects[bananalink][type] = "theme"
